C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe IlluminateShader.vert -o IlluminateShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe IlluminateShader.frag -o IlluminateShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe PlainShader.vert -o PlainShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe PlainShader.frag -o PlainShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe ParticleShader.vert -o ParticleShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe ParticleShader.frag -o ParticleShaderfrag.spv
c:/devs/gameengine/vulkan/vulkantest/libs/vulkansdk/1.3.261.0/bin/glslc.exe skyboxshader.vert -o skyboxshadervert.spv
c:/devs/gameengine/vulkan/vulkantest/libs/vulkansdk/1.3.261.0/bin/glslc.exe skyboxshader.frag -o skyboxshaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe TextureShader.vert -o TextureShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe TextureShader.frag -o TextureShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe GridShader.vert -o GridShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe GridShader.frag -o GridShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe CubemapShader.vert -o CubemapShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe CubemapShader.frag -o CubemapShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe ComputeShader.comp -o ComputeShadercomp.spv 
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe ComputeShader.vert -o ComputeShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe ComputeShader.frag -o ComputeShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe MandelbulbShader.vert -o MandelbulbShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe MandelbulbShader.frag -o MandelbulbShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe PBRShader.vert -o PBRShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe PBRShader.frag -o PBRShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe AimShader.vert -o AimShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe AimShader.frag -o AimShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe ReloadShader.vert -o ReloadShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe ReloadShader.frag -o ReloadShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe TextShader.vert -o TextShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe TextShader.frag -o TextShaderfrag.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe ButtonShader.vert -o ButtonShadervert.spv
C:/devs/gameengine/vulkan/VulkanTest/libs/VulkanSDK/1.3.261.0/Bin/glslc.exe ButtonShader.frag -o ButtonShaderfrag.spv
pause